# https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]