{% set name = "zeroc-ice" %}
{% set version = "3.7.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b063aafda360df711f76945529bb541576f266be41e5d5a2dd77f5d320c18664
  patches:
    - patch

build:
  number: 1
  skip: true  # [win]
  entry_points:
    - slice2py=slice2py:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - bzip2
    - openssl
    - libiconv
  run:
    - python
    - bzip2
    - openssl
    - libiconv

test:
  imports:
    - Glacier2
    - Ice
    - Ice.Py3
    - IceBox
    - IceGrid
    - IceMX
    - IcePatch2
    - IceStorm
  commands:
    - slice2py --help

about:
  home: https://zeroc.com
  license: GPL-2.0-only
  license_family: GPL2
  license_file:
    - ICE_LICENSE
  summary: Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more.

extra:
  recipe-maintainers:
    - psobolewskiphd
    - dpryan79
    - joshmoore
    - manics
