build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true
conda_build:
  pkg_format: '2'
test: native_and_emulated
